name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: pip install -r requirements.txt
    - name: make glove directory
      run: |
        mkdir -p ~/glove
    - name: Cache word2vec
      id: cache-word2vec
      uses: actions/cache@v2
      with:
        path: ~/glove/glove.6B.zip
        key: glove.6B.zip
    - name: Download GloVe vectors
      if: steps.cache-word2vec.outputs.cache-hit != 'true'
      run: |
        if [ ! -f "~/glove/glove.6B.zip" ]; then
          wget -P ~/glove http://nlp.stanford.edu/data/glove.6B.zip
        fi
    - name: Expand 50d vectors
      run: |
        if [ ! -f "~/glove/glove.6B.50d.txt" ]; then
          unzip -o -d ~/glove ~/glove/glove.6B.zip
        fi
    - name: Convert embeddings to SQLite database
      run: python embeddings2sqlite.py --embeddings-file ~/glove/glove.6B.50d.txt --sqlite-database ~/glove/glove.50d.sqlite --table glove --dimensionality 50 --commit-after 1000
    - name: Run GloVe Sanity Test
      run: python test_glove_sanity.py ~/glove/glove.50d.sqlite glove 50 dog.n.01
    - name: Upload SQLite database
      uses: actions/upload-artifact@v2
      with:
        name: glove.50d.sqlite
        path: ~/glove/glove.50d.sqlite
