name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: pip install -r requirements.txt
    - name: Download NLTK wordnet dataset
      run: python -c "import nltk; nltk.download('wordnet')"

